config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  get 'products/index'

  resources :products do
    resources :reviews, except: [:index, :new, :show]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord

  def price_in_dollars
  price_in_dollars = price_in_cents.to_f / 100
  sprintf("$%.2f", price_in_dollars)
end

    has_many :reviews
    validates :name, presence: true
    validates :description, presence: true
    validates :price_in_cents, presence: true
    validates :price_in_cents, numericality: true


end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :product
  validates :name, presence: true
  validates :description, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController


def action
end

def index
end

def new
end

def edit
end

def show
end

def update
end

def delete
end



end

app/controllers/products_controller.rb
class ProductsController < ApplicationController


def create
  @product = Product.new
  @product.name = params[:product][:name]
  @product.description = params[:product][:description]
  @product.price_in_cents = params[:product][:price_in_cents]

  if @product.save
    redirect_to product_path(@product)
  else
    render :new
  end
end

def index
  @products = Product.all
end

def new
  @product = Product.new

end

def edit
  @product = Product.find(params[:id])
end

def show
  @product = Product.find(params[:id])
  @reviews = @product.reviews
  @review = Review.new
end

def update
@product = Product.find(params[:id])
@product.name = params[:product][:name]
@product.description = params[:product][:description]
@product.price_in_cents = params[:product][:price_in_cents]

if @product.save
  redirect_to product_path(@product)
else
  render :new
end

end

def destroy
  @product = Product.find(params[:id])
  @product.destroy
  redirect_to "/products", notice: "Product deleted"

end



end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @review = Review.new
    @review.name = params[:review][:name]
    @review.text = params[:review][:text]
    @product = Product.find(params[:product_id])
    @review.product= @product

    if @review.save
      redirect_to product_path(@product)
    else
      render "products/show"
    end
  end

  def new
    @reviews = Review.new
  end

  def edit
    @review = Review.find(params[:id])
    @product = Product.find(params[:id])
    @review.product = @product
  end

  def update
  @review = Review.find(params[:id])
  @product = Product.find(params[:product_id])
  @review.product = @product
  @review.description = params[:review][:description]


  if @review.save
    redirect_to product_path(@product)
  else
    render edit_product_review_path
  end

  end


  def destroy
    @review = Review.find(params[:id])
    @product = Product.find(params[:product_id])
    @review.product = @product
    @review.destroy

    redirect_to product_path
  end
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rainforest</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
     <ul>
       <li><%= link_to 'Home', products_path %></li>
       <li><%= link_to 'New Product', new_product_path %></li>
     </ul>
   </nav>
   <% if flash[:notice] %>
      <p class="notice"><%= flash[:notice] %></p>
    <% end %>
    <% if flash[:alert] %>
      <p class="alert"><%= flash[:alert] %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for [@product] do |f| %>
 <%= f.label :name %>:
 <%= f.text_field :name %>

 <%= f.label  :description %>
 <%= f.text_field  :description %>

 <%= f.label :price %>
 <%= f.text_field :price_in_cents %>
<%= f.submit %>
<% end %>

app/views/products/edit.html.erb
<%= render 'form', product: @product %>

app/views/products/index.html.erb
<h1>Display Products</h1>
<section class="products"
<% @products.each do |product| %>
  <section class="product"
  <p class="product-name"> <%= product.name %> </p>
  <%= link_to("View Product", product_path(product)) %>
  <p class="description"> <%= product.description %> </p>
  <p class="price"> <%= product.price_in_cents %>&cent; </p>
  </section>
<% end %>
</section>

<p>
  <%= link_to 'New Product', new_product_path %>
</p>

<!-- !-- <h1>Display Events</h1> -->

app/views/products/new.html.erb
<%= @product.errors.full_messages %>

<%= render 'form', product: @product %>

app/views/products/show.html.erb
<section class="show-product">
  <p> <%= @product.name %> </p>
  <p> <%= @product.description %> </p>
  <p> <%= @product.price_in_cents %> </p>
  <p> <button type ="button"><%= link_to 'Edit', edit_product_path(@product) %> </button>
      <button type ="button" <%= link_to 'Delete', product_path(@product), method: :delete, data: {confirm: "Are you sure?" } %> </button>
  </p>


<h2> Reviews </h2>

<ul>
    <% @reviews.each do |review| %>
      <li>
        <p>On <%= review.created_at %> <%= review.name %> said: </p>
        <p> <%= review.text %> </p>
      </li>
      <p> <button type ="button"><%= link_to 'Edit', edit_product_review_path(@product, review) %> </button>
          <button type ="button" <%= link_to 'Delete', product_review_path(@product, review), method: :delete, data: {confirm: "Are you sure?" } %> </button>
      </p>
    <% end %>
</ul>

<%= form_for [@product, @review] do |f| %>
 <%= f.label :name %>:
 <%= f.text_field :name %><br />

 <%= f.label :text%>:
 <%= f.text_field :text %><br />

 <%= f.submit %>
<% end %>